### PR TITLE
Agavgavi/ticket detail

### PR DESCRIPTION
**Pull request by agavgavi**
Finished Ticket List Detail:
- Ticket list is a NavView List of tickets
- Ticket Pill represents the UI for a ticket row
- Ticket list is searchable, refreshable
- Ticket list can be filtered by Assigned User, Status, or Tag
- Ticket List has infinite scrolling, as soon as you get to the end of one page it will load the rest.
- Ticket list uses MVVM separating information from Views

### CODE REVIEW

**Comment by tebertt** [comment]
Everything looks really good. Currently you can only select one filter per type (so you can't filter by to-do and in-progress at the same time). Also, should we try to persist filters when the app is closed?

**Comment by agavgavi** [comment]
> Currently you can only select one filter per type (so you can't filter by to-do and in-progress at the same time). 

That is how it was in the last one, I'm not sure if the database supports multiple queries of the same filter type but I can check if we want.


> Also, should we try to persist filters when the app is closed? 

I can look into that, could be stored to appIdentity but I feel like filters being different per team shouldn't be persistent.

**Review by tebertt — APPROVED** [review]
Looks good

**Review by tebertt — APPROVED** [review]
Approved

**Pull request merged**
