### PR TITLE
Smarti84/ticket creation

### PR DESCRIPTION
**Pull request by Firestarsam**
- Created the ability to create tickets from a modal view in the List Controller
- In this create tickets modal, the user can set the name, description, assigned user, and whether or not they want a due date, plus the due date itself.
- In addition, the Ticket Detail View is based on the create view, and will populate the data when you click on the ticket.
- Tickets can be edited in the detail view and be saved/written to the server

Issues:

- JsonLoader has a bug where if we want to send a nil on purpose (for example removing a due date), it won't encode and sent it, thus leaving outdated information on tickets.
- Sometimes the TicketList view will essentially segfault with an index out of bounds error; we haven't touched anything in there besides calling `pushviewcontroller` function and calling the `HandleRefresh` function, so we aren't sure what is causing this issue.

### CODE REVIEW

**Comment by agavgavi** [comment]
Conflict is in xcode project file, but I'm way to tired to deal with this. Someone else can pick current/incoming

**Review by tdimhcsleumas — APPROVED** [review]
Should be good enough for now. Copying over from discord:

* design doesn't really work on smaller screens
* I think the description boxes should go below ui items which have a fixed height (like the due data and assigned user selector)

**Comment by agavgavi** [comment]
Both of these changes will be produced tomorrow at the start of next sprint.

**Comment by tdimhcsleumas** [comment]
> Both of these changes will be produced tomorrow at the start of next sprint.

To merge or not to merge?

**Comment by agavgavi** [comment]
They will be a seperate PR

**Review by tdimhcsleumas — CHANGES_REQUESTED** [review]
Forgot about the ticket list bug. Holding off merge until that gets fixed.

**Review by tdimhcsleumas — APPROVED** [review]

**Pull request merged**
